version: '3'
services:
  sellers:
    container_name: sellers
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
        - 17100:17100
    networks:
        - web

networks:
  web:
      external: true