base_path: /api
env_path: ".env"
app_port: ":17100"

allowed:
  hosts:
    - "http://localhost:8080"

postgres:
  use: true
  username: "postgres"
  host: "postgres"
  port: "10100"
  db_name: "smdm"
  ssl_mode: "disable"
