base_path: /api
env_path: ".env"

allowed:
  hosts:
    - "http://localhost:8080"

postgres:
  use: true
  username: "postgres"
  host: "localhost"
  port: "5432"
  db_name: "prodmdm"
  ssl_mode: "disable"
