openapi: 3.0.3
info:
  title: Fox Converter
  description: Fox Converter API for data conversion
  version: 1.0.0

servers:
  - url: 'https'

paths:

  /v1/sellers:
    post:
      description: Create new Seller data record
      operationId: postNewSeller
      security:
        - Keycloak:
          - sellers:write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/NewSellerRequest"
      responses:
        '200':
          description: Ok

  /v1/sellers/id/{id}:
    get:
      description: Get seller data from DB by id
      operationId: getSeller
      security:
        - Keycloak:
          - sellers:read
      parameters:
        - name: id
          required: true
          in: path
          description: Id of seller
          schema:
            type: string
            format: URLs
          x-go-param-name: URLParams
      responses:
        '200':
          description: Seller Data in JSON Format
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SellerResponse"

    put:
      description: Edit Seller data record
      operationId: putSeller
      security:
        - Keycloak:
          - sellers:write
      parameters:
        - name: id
          required: true
          in: path
          description: Id of seller
          schema:
            type: string
            format: uuid
          x-go-param-name: URLParams
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/EditSellerRequest"
      responses:
        '200':
          description: Ok

    delete:
      description: Delete Seller data record
      operationId: deleteSeller
      security:
        - Keycloak:
          - sellers:delete
      parameters:
        - name: id
          required: true
          in: path
          description: Id of seller
          schema:
            type: string
            format: uuid
          x-go-param-name: URLParams
      responses:
        '200':
          description: Ok

  /v1/sellers/all:
    get:
      description: Get all seller's Ids
      operationId: GetSellersAll
      security:
        - Keycloak:
          - sellers:read
      responses:
        '200':
          description: Seller Data in JSON Format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SellerResponse"

  /v1/sellers/search:
    get:
      description: Get seller data from DB by name
      operationId: getSellersByName
      security:
        - Keycloak:
          - sellers:read
      parameters:
        - name: name
          required: true
          in: query
          description: name of seller
          schema:
            type: string
      responses:
        '200':
          description: Seller Data in JSON Format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SellerResponse"


components:
  securitySchemes:
    Keycloak:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: 'http://'
          tokenUrl: 'http://'
          scopes:
            sellers:read: "Read sellers"
            sellers:write: "Change and delete sellers"
      description: OAuth2 client credentials grant flow with Keycloak
  
  schemas:
    
    NewSellerRequest:
      type: object
      description: Seller Master Data
      properties:
        id:
          type: string
          format: uuid
        city:
          type: string
        inn:
          type: string
        logo:
          type: string
        memo:
          type: string
        name:
          type: string
        ogrn:
          type: string
        site:
          type: string
        yml:
          type: string
    
    EditSellerRequest:
      allOf:
        - $ref: "#/components/schemas/NewSellerRequest"
        - type: object
          description: Seller Master Data
          required:
            - "id"

    SellerResponse:
      allOf:
        - $ref: "#/components/schemas/EditSellerRequest"
        - type: object
          description: Seller Master Data
          properties:
            created:
              type: string
            updated:
              type: string
